version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "feelepxyz"
    automerged_updates:
      - match:
          dependency_type: "development"
          kind: "semver:minor"
      - match:
          dependency_type: "production"
          kind: "semver:patch"
